package fi.csc.avaa.kotus.kielikartastot.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Aineisto service. Represents a row in the &quot;aineisto&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link fi.csc.avaa.kotus.kielikartastot.db.model.impl.AineistoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link fi.csc.avaa.kotus.kielikartastot.db.model.impl.AineistoImpl}.
 * </p>
 *
 * @author CSC
 * @see Aineisto
 * @see fi.csc.avaa.kotus.kielikartastot.db.model.impl.AineistoImpl
 * @see fi.csc.avaa.kotus.kielikartastot.db.model.impl.AineistoModelImpl
 * @generated
 */
public interface AineistoModel extends BaseModel<Aineisto> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a aineisto model instance should use the {@link Aineisto} interface instead.
     */

    /**
     * Returns the primary key of this aineisto.
     *
     * @return the primary key of this aineisto
     */
    public int getPrimaryKey();

    /**
     * Sets the primary key of this aineisto.
     *
     * @param primaryKey the primary key of this aineisto
     */
    public void setPrimaryKey(int primaryKey);

    /**
     * Returns the aineisto_id of this aineisto.
     *
     * @return the aineisto_id of this aineisto
     */
    public int getAineisto_id();

    /**
     * Sets the aineisto_id of this aineisto.
     *
     * @param aineisto_id the aineisto_id of this aineisto
     */
    public void setAineisto_id(int aineisto_id);

    /**
     * Returns the nimi of this aineisto.
     *
     * @return the nimi of this aineisto
     */
    @AutoEscape
    public String getNimi();

    /**
     * Sets the nimi of this aineisto.
     *
     * @param nimi the nimi of this aineisto
     */
    public void setNimi(String nimi);

    /**
     * Returns the tunnus of this aineisto.
     *
     * @return the tunnus of this aineisto
     */
    @AutoEscape
    public String getTunnus();

    /**
     * Sets the tunnus of this aineisto.
     *
     * @param tunnus the tunnus of this aineisto
     */
    public void setTunnus(String tunnus);

    /**
     * Returns the kuvaus of this aineisto.
     *
     * @return the kuvaus of this aineisto
     */
    @AutoEscape
    public String getKuvaus();

    /**
     * Sets the kuvaus of this aineisto.
     *
     * @param kuvaus the kuvaus of this aineisto
     */
    public void setKuvaus(String kuvaus);

    /**
     * Returns the paikkatietosysteemi of this aineisto.
     *
     * @return the paikkatietosysteemi of this aineisto
     */
    @AutoEscape
    public String getPaikkatietosysteemi();

    /**
     * Sets the paikkatietosysteemi of this aineisto.
     *
     * @param paikkatietosysteemi the paikkatietosysteemi of this aineisto
     */
    public void setPaikkatietosysteemi(String paikkatietosysteemi);

    /**
     * Returns the infolinkki of this aineisto.
     *
     * @return the infolinkki of this aineisto
     */
    @AutoEscape
    public String getInfolinkki();

    /**
     * Sets the infolinkki of this aineisto.
     *
     * @param infolinkki the infolinkki of this aineisto
     */
    public void setInfolinkki(String infolinkki);

    /**
     * Returns the kayttolupa of this aineisto.
     *
     * @return the kayttolupa of this aineisto
     */
    @AutoEscape
    public String getKayttolupa();

    /**
     * Sets the kayttolupa of this aineisto.
     *
     * @param kayttolupa the kayttolupa of this aineisto
     */
    public void setKayttolupa(String kayttolupa);

    /**
     * Returns the tuotu_kantaan of this aineisto.
     *
     * @return the tuotu_kantaan of this aineisto
     */
    public Date getTuotu_kantaan();

    /**
     * Sets the tuotu_kantaan of this aineisto.
     *
     * @param tuotu_kantaan the tuotu_kantaan of this aineisto
     */
    public void setTuotu_kantaan(Date tuotu_kantaan);

    /**
     * Returns the muutettu of this aineisto.
     *
     * @return the muutettu of this aineisto
     */
    public Date getMuutettu();

    /**
     * Sets the muutettu of this aineisto.
     *
     * @param muutettu the muutettu of this aineisto
     */
    public void setMuutettu(Date muutettu);

    /**
     * Returns the muuttaja of this aineisto.
     *
     * @return the muuttaja of this aineisto
     */
    @AutoEscape
    public String getMuuttaja();

    /**
     * Sets the muuttaja of this aineisto.
     *
     * @param muuttaja the muuttaja of this aineisto
     */
    public void setMuuttaja(String muuttaja);

    /**
     * Returns the poistettu of this aineisto.
     *
     * @return the poistettu of this aineisto
     */
    public Date getPoistettu();

    /**
     * Sets the poistettu of this aineisto.
     *
     * @param poistettu the poistettu of this aineisto
     */
    public void setPoistettu(Date poistettu);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(Aineisto aineisto);

    @Override
    public int hashCode();

    @Override
    public CacheModel<Aineisto> toCacheModel();

    @Override
    public Aineisto toEscapedModel();

    @Override
    public Aineisto toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
