package fi.csc.avaa.kotus.kielikartastot.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Ilmio service. Represents a row in the &quot;ilmio&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link fi.csc.avaa.kotus.kielikartastot.db.model.impl.IlmioModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link fi.csc.avaa.kotus.kielikartastot.db.model.impl.IlmioImpl}.
 * </p>
 *
 * @author CSC
 * @see Ilmio
 * @see fi.csc.avaa.kotus.kielikartastot.db.model.impl.IlmioImpl
 * @see fi.csc.avaa.kotus.kielikartastot.db.model.impl.IlmioModelImpl
 * @generated
 */
public interface IlmioModel extends BaseModel<Ilmio> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a ilmio model instance should use the {@link Ilmio} interface instead.
     */

    /**
     * Returns the primary key of this ilmio.
     *
     * @return the primary key of this ilmio
     */
    public int getPrimaryKey();

    /**
     * Sets the primary key of this ilmio.
     *
     * @param primaryKey the primary key of this ilmio
     */
    public void setPrimaryKey(int primaryKey);

    /**
     * Returns the ilmio_id of this ilmio.
     *
     * @return the ilmio_id of this ilmio
     */
    public int getIlmio_id();

    /**
     * Sets the ilmio_id of this ilmio.
     *
     * @param ilmio_id the ilmio_id of this ilmio
     */
    public void setIlmio_id(int ilmio_id);

    /**
     * Returns the aineisto_id of this ilmio.
     *
     * @return the aineisto_id of this ilmio
     */
    public int getAineisto_id();

    /**
     * Sets the aineisto_id of this ilmio.
     *
     * @param aineisto_id the aineisto_id of this ilmio
     */
    public void setAineisto_id(int aineisto_id);

    /**
     * Returns the ryhma_id of this ilmio.
     *
     * @return the ryhma_id of this ilmio
     */
    public int getRyhma_id();

    /**
     * Sets the ryhma_id of this ilmio.
     *
     * @param ryhma_id the ryhma_id of this ilmio
     */
    public void setRyhma_id(int ryhma_id);

    /**
     * Returns the lajikoodi_id of this ilmio.
     *
     * @return the lajikoodi_id of this ilmio
     */
    public int getLajikoodi_id();

    /**
     * Sets the lajikoodi_id of this ilmio.
     *
     * @param lajikoodi_id the lajikoodi_id of this ilmio
     */
    public void setLajikoodi_id(int lajikoodi_id);

    /**
     * Returns the ilmio of this ilmio.
     *
     * @return the ilmio of this ilmio
     */
    @AutoEscape
    public String getIlmio();

    /**
     * Sets the ilmio of this ilmio.
     *
     * @param ilmio the ilmio of this ilmio
     */
    public void setIlmio(String ilmio);

    /**
     * Returns the tyyppi of this ilmio.
     *
     * @return the tyyppi of this ilmio
     */
    @AutoEscape
    public String getTyyppi();

    /**
     * Sets the tyyppi of this ilmio.
     *
     * @param tyyppi the tyyppi of this ilmio
     */
    public void setTyyppi(String tyyppi);

    /**
     * Returns the kieli_ i s o639_3 of this ilmio.
     *
     * @return the kieli_ i s o639_3 of this ilmio
     */
    @AutoEscape
    public String getKieli_ISO639_3();

    /**
     * Sets the kieli_ i s o639_3 of this ilmio.
     *
     * @param kieli_ISO639_3 the kieli_ i s o639_3 of this ilmio
     */
    public void setKieli_ISO639_3(String kieli_ISO639_3);

    /**
     * Returns the murre of this ilmio.
     *
     * @return the murre of this ilmio
     */
    @AutoEscape
    public String getMurre();

    /**
     * Sets the murre of this ilmio.
     *
     * @param murre the murre of this ilmio
     */
    public void setMurre(String murre);

    /**
     * Returns the havaintoaika of this ilmio.
     *
     * @return the havaintoaika of this ilmio
     */
    @AutoEscape
    public String getHavaintoaika();

    /**
     * Sets the havaintoaika of this ilmio.
     *
     * @param havaintoaika the havaintoaika of this ilmio
     */
    public void setHavaintoaika(String havaintoaika);

    /**
     * Returns the kuvaus of this ilmio.
     *
     * @return the kuvaus of this ilmio
     */
    @AutoEscape
    public String getKuvaus();

    /**
     * Sets the kuvaus of this ilmio.
     *
     * @param kuvaus the kuvaus of this ilmio
     */
    public void setKuvaus(String kuvaus);

    /**
     * Returns the lisatieto of this ilmio.
     *
     * @return the lisatieto of this ilmio
     */
    @AutoEscape
    public String getLisatieto();

    /**
     * Sets the lisatieto of this ilmio.
     *
     * @param lisatieto the lisatieto of this ilmio
     */
    public void setLisatieto(String lisatieto);

    /**
     * Returns the tuotu_kantaan of this ilmio.
     *
     * @return the tuotu_kantaan of this ilmio
     */
    public Date getTuotu_kantaan();

    /**
     * Sets the tuotu_kantaan of this ilmio.
     *
     * @param tuotu_kantaan the tuotu_kantaan of this ilmio
     */
    public void setTuotu_kantaan(Date tuotu_kantaan);

    /**
     * Returns the muutettu of this ilmio.
     *
     * @return the muutettu of this ilmio
     */
    public Date getMuutettu();

    /**
     * Sets the muutettu of this ilmio.
     *
     * @param muutettu the muutettu of this ilmio
     */
    public void setMuutettu(Date muutettu);

    /**
     * Returns the muuttaja of this ilmio.
     *
     * @return the muuttaja of this ilmio
     */
    @AutoEscape
    public String getMuuttaja();

    /**
     * Sets the muuttaja of this ilmio.
     *
     * @param muuttaja the muuttaja of this ilmio
     */
    public void setMuuttaja(String muuttaja);

    /**
     * Returns the poistettu of this ilmio.
     *
     * @return the poistettu of this ilmio
     */
    public Date getPoistettu();

    /**
     * Sets the poistettu of this ilmio.
     *
     * @param poistettu the poistettu of this ilmio
     */
    public void setPoistettu(Date poistettu);

    /**
     * Returns the tunnus of this ilmio.
     *
     * @return the tunnus of this ilmio
     */
    @AutoEscape
    public String getTunnus();

    /**
     * Sets the tunnus of this ilmio.
     *
     * @param tunnus the tunnus of this ilmio
     */
    public void setTunnus(String tunnus);

    /**
     * Returns the ryhma_tunnus of this ilmio.
     *
     * @return the ryhma_tunnus of this ilmio
     */
    @AutoEscape
    public String getRyhma_tunnus();

    /**
     * Sets the ryhma_tunnus of this ilmio.
     *
     * @param ryhma_tunnus the ryhma_tunnus of this ilmio
     */
    public void setRyhma_tunnus(String ryhma_tunnus);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(Ilmio ilmio);

    @Override
    public int hashCode();

    @Override
    public CacheModel<Ilmio> toCacheModel();

    @Override
    public Ilmio toEscapedModel();

    @Override
    public Ilmio toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
