package fi.csc.avaa.kotus.kielikartastot.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Lajikoodi service. Represents a row in the &quot;lajikoodi&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link fi.csc.avaa.kotus.kielikartastot.db.model.impl.LajikoodiModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link fi.csc.avaa.kotus.kielikartastot.db.model.impl.LajikoodiImpl}.
 * </p>
 *
 * @author CSC
 * @see Lajikoodi
 * @see fi.csc.avaa.kotus.kielikartastot.db.model.impl.LajikoodiImpl
 * @see fi.csc.avaa.kotus.kielikartastot.db.model.impl.LajikoodiModelImpl
 * @generated
 */
public interface LajikoodiModel extends BaseModel<Lajikoodi> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a lajikoodi model instance should use the {@link Lajikoodi} interface instead.
     */

    /**
     * Returns the primary key of this lajikoodi.
     *
     * @return the primary key of this lajikoodi
     */
    public int getPrimaryKey();

    /**
     * Sets the primary key of this lajikoodi.
     *
     * @param primaryKey the primary key of this lajikoodi
     */
    public void setPrimaryKey(int primaryKey);

    /**
     * Returns the lajikoodi_id of this lajikoodi.
     *
     * @return the lajikoodi_id of this lajikoodi
     */
    public int getLajikoodi_id();

    /**
     * Sets the lajikoodi_id of this lajikoodi.
     *
     * @param lajikoodi_id the lajikoodi_id of this lajikoodi
     */
    public void setLajikoodi_id(int lajikoodi_id);

    /**
     * Returns the lajikoodi of this lajikoodi.
     *
     * @return the lajikoodi of this lajikoodi
     */
    public int getLajikoodi();

    /**
     * Sets the lajikoodi of this lajikoodi.
     *
     * @param lajikoodi the lajikoodi of this lajikoodi
     */
    public void setLajikoodi(int lajikoodi);

    /**
     * Returns the laji of this lajikoodi.
     *
     * @return the laji of this lajikoodi
     */
    @AutoEscape
    public String getLaji();

    /**
     * Sets the laji of this lajikoodi.
     *
     * @param laji the laji of this lajikoodi
     */
    public void setLaji(String laji);

    /**
     * Returns the aineistot of this lajikoodi.
     *
     * @return the aineistot of this lajikoodi
     */
    @AutoEscape
    public String getAineistot();

    /**
     * Sets the aineistot of this lajikoodi.
     *
     * @param aineistot the aineistot of this lajikoodi
     */
    public void setAineistot(String aineistot);

    /**
     * Returns the viite of this lajikoodi.
     *
     * @return the viite of this lajikoodi
     */
    @AutoEscape
    public String getViite();

    /**
     * Sets the viite of this lajikoodi.
     *
     * @param viite the viite of this lajikoodi
     */
    public void setViite(String viite);

    /**
     * Returns the tuotu_kantaan of this lajikoodi.
     *
     * @return the tuotu_kantaan of this lajikoodi
     */
    public Date getTuotu_kantaan();

    /**
     * Sets the tuotu_kantaan of this lajikoodi.
     *
     * @param tuotu_kantaan the tuotu_kantaan of this lajikoodi
     */
    public void setTuotu_kantaan(Date tuotu_kantaan);

    /**
     * Returns the muutettu of this lajikoodi.
     *
     * @return the muutettu of this lajikoodi
     */
    public Date getMuutettu();

    /**
     * Sets the muutettu of this lajikoodi.
     *
     * @param muutettu the muutettu of this lajikoodi
     */
    public void setMuutettu(Date muutettu);

    /**
     * Returns the muuttaja of this lajikoodi.
     *
     * @return the muuttaja of this lajikoodi
     */
    @AutoEscape
    public String getMuuttaja();

    /**
     * Sets the muuttaja of this lajikoodi.
     *
     * @param muuttaja the muuttaja of this lajikoodi
     */
    public void setMuuttaja(String muuttaja);

    /**
     * Returns the poistettu of this lajikoodi.
     *
     * @return the poistettu of this lajikoodi
     */
    public Date getPoistettu();

    /**
     * Sets the poistettu of this lajikoodi.
     *
     * @param poistettu the poistettu of this lajikoodi
     */
    public void setPoistettu(Date poistettu);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(Lajikoodi lajikoodi);

    @Override
    public int hashCode();

    @Override
    public CacheModel<Lajikoodi> toCacheModel();

    @Override
    public Lajikoodi toEscapedModel();

    @Override
    public Lajikoodi toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
