package fi.csc.avaa.kotus.kielikartastot.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Levikki service. Represents a row in the &quot;levikki&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link fi.csc.avaa.kotus.kielikartastot.db.model.impl.LevikkiModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link fi.csc.avaa.kotus.kielikartastot.db.model.impl.LevikkiImpl}.
 * </p>
 *
 * @author CSC
 * @see Levikki
 * @see fi.csc.avaa.kotus.kielikartastot.db.model.impl.LevikkiImpl
 * @see fi.csc.avaa.kotus.kielikartastot.db.model.impl.LevikkiModelImpl
 * @generated
 */
public interface LevikkiModel extends BaseModel<Levikki> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a levikki model instance should use the {@link Levikki} interface instead.
     */

    /**
     * Returns the primary key of this levikki.
     *
     * @return the primary key of this levikki
     */
    public int getPrimaryKey();

    /**
     * Sets the primary key of this levikki.
     *
     * @param primaryKey the primary key of this levikki
     */
    public void setPrimaryKey(int primaryKey);

    /**
     * Returns the levikki_id of this levikki.
     *
     * @return the levikki_id of this levikki
     */
    public int getLevikki_id();

    /**
     * Sets the levikki_id of this levikki.
     *
     * @param levikki_id the levikki_id of this levikki
     */
    public void setLevikki_id(int levikki_id);

    /**
     * Returns the ilmio_id of this levikki.
     *
     * @return the ilmio_id of this levikki
     */
    public int getIlmio_id();

    /**
     * Sets the ilmio_id of this levikki.
     *
     * @param ilmio_id the ilmio_id of this levikki
     */
    public void setIlmio_id(int ilmio_id);

    /**
     * Returns the paikka_id of this levikki.
     *
     * @return the paikka_id of this levikki
     */
    public int getPaikka_id();

    /**
     * Sets the paikka_id of this levikki.
     *
     * @param paikka_id the paikka_id of this levikki
     */
    public void setPaikka_id(int paikka_id);

    /**
     * Returns the paikka_tunniste of this levikki.
     *
     * @return the paikka_tunniste of this levikki
     */
    @AutoEscape
    public String getPaikka_tunniste();

    /**
     * Sets the paikka_tunniste of this levikki.
     *
     * @param paikka_tunniste the paikka_tunniste of this levikki
     */
    public void setPaikka_tunniste(String paikka_tunniste);

    /**
     * Returns the ilmio_tunnus of this levikki.
     *
     * @return the ilmio_tunnus of this levikki
     */
    @AutoEscape
    public String getIlmio_tunnus();

    /**
     * Sets the ilmio_tunnus of this levikki.
     *
     * @param ilmio_tunnus the ilmio_tunnus of this levikki
     */
    public void setIlmio_tunnus(String ilmio_tunnus);

    /**
     * Returns the uusi of this levikki.
     *
     * @return the uusi of this levikki
     */
    public int getUusi();

    /**
     * Sets the uusi of this levikki.
     *
     * @param uusi the uusi of this levikki
     */
    public void setUusi(int uusi);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(Levikki levikki);

    @Override
    public int hashCode();

    @Override
    public CacheModel<Levikki> toCacheModel();

    @Override
    public Levikki toEscapedModel();

    @Override
    public Levikki toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
