package fi.csc.avaa.kotus.kielikartastot.db.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import fi.csc.avaa.kotus.kielikartastot.db.model.Ilmio;
import fi.csc.avaa.kotus.kielikartastot.db.service.IlmioLocalServiceUtil;

/**
 * The extended model base implementation for the Ilmio service. Represents a row in the &quot;ilmio&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link IlmioImpl}.
 * </p>
 *
 * @author CSC
 * @see IlmioImpl
 * @see fi.csc.avaa.kotus.kielikartastot.db.model.Ilmio
 * @generated
 */
public abstract class IlmioBaseImpl extends IlmioModelImpl implements Ilmio {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a ilmio model instance should use the {@link Ilmio} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            IlmioLocalServiceUtil.addIlmio(this);
        } else {
            IlmioLocalServiceUtil.updateIlmio(this);
        }
    }
}
