package fi.csc.avaa.kotus.kielikartastot.db.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import fi.csc.avaa.kotus.kielikartastot.db.model.Lajikoodi;
import fi.csc.avaa.kotus.kielikartastot.db.service.LajikoodiLocalServiceUtil;

/**
 * The extended model base implementation for the Lajikoodi service. Represents a row in the &quot;lajikoodi&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LajikoodiImpl}.
 * </p>
 *
 * @author CSC
 * @see LajikoodiImpl
 * @see fi.csc.avaa.kotus.kielikartastot.db.model.Lajikoodi
 * @generated
 */
public abstract class LajikoodiBaseImpl extends LajikoodiModelImpl
    implements Lajikoodi {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a lajikoodi model instance should use the {@link Lajikoodi} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            LajikoodiLocalServiceUtil.addLajikoodi(this);
        } else {
            LajikoodiLocalServiceUtil.updateLajikoodi(this);
        }
    }
}
