package fi.csc.avaa.kotus.kielikartastot.db.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import fi.csc.avaa.kotus.kielikartastot.db.model.Ryhma;
import fi.csc.avaa.kotus.kielikartastot.db.service.RyhmaLocalServiceUtil;

/**
 * The extended model base implementation for the Ryhma service. Represents a row in the &quot;ryhma&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RyhmaImpl}.
 * </p>
 *
 * @author CSC
 * @see RyhmaImpl
 * @see fi.csc.avaa.kotus.kielikartastot.db.model.Ryhma
 * @generated
 */
public abstract class RyhmaBaseImpl extends RyhmaModelImpl implements Ryhma {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a ryhma model instance should use the {@link Ryhma} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            RyhmaLocalServiceUtil.addRyhma(this);
        } else {
            RyhmaLocalServiceUtil.updateRyhma(this);
        }
    }
}
